### ISSUE TITLE
Could davis.js check for the pushstate browser capability?

### ISSUE THREAD

**Issue by cmalven** [olivernn/davis.js#1]
You state that davis will currently fail hard in a browser that doesn't support HTML5 push state. Is it possible for davis to initially check the browser for support of push state, and if it doesn't support it just fallback to treating all links just normal links (exactly like what would happen without javascript enabled)?

It seems to me this would be very much preferable to failing hard in browsers without good HTML5 support, assuming testing for this capability is even possible. If this is crazy talk, please just let me know.

**Comment by olivernn** [comment]
Yes, being able to degrade gracefully is the goal.

I was thinking of checking for support, if its not available all links and forms will work as they would without JavaScript.  Will also fire an event so that you can have some custom logic to handle those browsers that do not handle pushState.

**Comment by cmalven** [comment]
I'm looking forward to seeing this implemented.

**Comment by olivernn** [comment]
This has been implemented in 0.2.0.  An app will not start if there is no pushState support, all links and forms will have their default behaviour and a 'unsupported' event will be fired.
