### ISSUE TITLE
originChecks of Davis.listener don't work correctly in IE8

### ISSUE THREAD

**Issue by jacobcoens** [olivernn/davis.js#25]
As the originCheck checks against the host property of the hyperlink, (in some cases) the port number is included whereas it is not included in the host property of window.location.

I've fixed this by using the hostname property of the hyperlink in stead of the host property.

Also, I think the protocols should match so that linking to and from the https-secured site will result in a page refresh.

This would result in the following for line 220 of davis.js
      return elem.hostname !== window.location.host || elem.protocol !== window.location.protocol

**Comment by olivernn** [comment]
Hey that sounds good, could you put this together into a pull request?  Then I can add this into the next release.

**Comment by olivernn** [comment]
fixed in the latest release
