### ISSUE TITLE
Ignore page anchor href

### ISSUE THREAD

**Issue by rstmsn** [olivernn/davis.js#30]

**Comment by olivernn** [comment]
By default Davis binds to all links and all forms, you can change this behaviour by changing the linkSelector setting.  For your example you could do something like this:

```
app = Davis(function () {
  // your routes etc

  this.configure(function () {
    this.linkSelector = 'a.not([href="#"])'
  })
})
```

I haven't tried that selector, but the idea is to not bind to any links with an href of '#'.

**Comment by dumbmatter** [comment]
In case anyone else winds up here from Google, the above code doesn't seem to work, but it does work if I change it to:

```
    this.linkSelector = 'a:not([href="#"])';
```

**Comment by olivernn** [comment]
Argh yeah, stupid typo, the full code snippet is:

```
app = Davis(function () {

  // your routes here

  this.configure(function () {
    this.linkSelector = 'a:not([href="#"])'
  })
})
```

Thanks @jdscheff for pointing this out.
