### ISSUE TITLE
Greeter example from davisjs.com broken

### ISSUE THREAD

**Issue by iainxt** [olivernn/davis.js#31]
Hi, 

The example fails to load the davis.js file with github returning a 404.

Thanks,

Iain

**Comment by iainxt** [comment]
I tried coping the code to my local server and using the latest davis.js, but it doesn't work. It hits the server each time :(

**Comment by olivernn** [comment]
Thanks, it was using quite an old version of Davis, I'll update the example to use the latest version.

Whilst testing this I found a bug myself in the code, it might be causing the issue you are seeing, when handling links etc it checks that the origin of the link matches the origin of the current page, however it was including the port number for the page origin and not the link origin, which means if you were running the example on a port then it wouldn't think the link is on the same origin as the page and so ignores it, I've opened an issue for this here https://github.com/olivernn/davis.js/issues/32

**Comment by iainxt** [comment]
I did use a port locally, so I certainly hope so. I'll give it another go soon :)

**Comment by olivernn** [comment]
I've released a new version of Davis which fixes this issue and updated the greeter example app to use this version, all should work fine now.

**Comment by iainxt** [comment]
It works :) Thanks. The hair I pulled out is slowing growing back :op
