### ISSUE TITLE
iOS - First link fires correct push state, the rest fail

### ISSUE THREAD

**Issue by TomSlezakowski** [olivernn/davis.js#41]
Hey!

After playing around with Davis in one of your other projects I decided to use it on a new project from the outset, however I am experiencing a problem with iOS devices. I've tested this on iPhone 4 and iPad 3.

Davis correctly runs and attaches itself to links, when I click a routed link, the push state happens and all is well, however all subsequent links do not fire and no change of state happens.

It's relatively barebones so far so this is really all the code I can provide :)

``` javascript

var app = Davis(function() {

    this.use(Davis.googleAnalytics);

    this.get('/game/:game_id', function (req) {
        console.log("@ section " + req.params['game_id']);
    });

});

app.start();
```

**Comment by TomSlezakowski** [comment]
Hmm. Sorry. Nothing to do with Davis at all. Everything to do with buggy Safari. Apologies! :D

**Comment by olivernn** [comment]
No worries, is this a bug with mobile Safari's pushState handling?  In older versions it did have a few bugs, however I thought these had been fixed in the latest versions.
