### ISSUE TITLE
3 small issues with the plugin docs

### ISSUE THREAD

**Issue by mahonnaise** [olivernn/davis.js#45]
http://davisjs.com/plugins

1. Syntax error

``` javascript
var Davis.greeter = function () { // you can't have "var" there
    [...]
}
```

2. Looks like a constructor (it's capitalized), but there is no `new`.

``` javascript
var app = Davis(function () {
    [...]
}
```

Does it work with `new`?

3. Link to _davis.fblike.js_ is labeled "Davis.noIOS".

**Comment by olivernn** [comment]
Thanks for bring this to my attention, I've updated the site documentation.

Regarding point 2, the Davis function is not a constructor, it acts as both a namespace for the rest of the objects that make up the library as well as a function for quickly declaring your app's routes.

I totally agree that it shouldn't be capitalised as its not a constructor, this may be something that will change in a 1.x release, but until then I can't really change this without breaking a lot of peoples apps.
