### ISSUE TITLE
Router's before and after methods are not scoped.

### ISSUE THREAD

**Issue by ali-sattari** [olivernn/davis.js#54]
Scope isn't applied to _before_ and _after_ methods in Davis.Router, making it confusing for path specific calls.

This works:

``` javascript
app = Davis(function(){
    this.scope('/myapp');

    this.before('/myapp', function(req){
        console.log('before /', req);
    });
    this.get('/', function(req){
        console.log('get /', req);
    });
});
```

While this should work:

``` javascript
app = Davis(function(){
    this.scope('/myapp');

    this.before('/', function(req){
        console.log('before /', req);
    });
    this.get('/', function(req){
        console.log('get /', req);
    });
});
```

The issue can be solved by changing filter method of Davis.Router to add scope to the path when there is 2 arguments.

**Comment by olivernn** [comment]
Good catch, I've just pushed a new version (0.9.4) of the library with a fix for this, thanks.
