### ISSUE TITLE
Manually trigger or parse a route

### ISSUE THREAD

**Issue by ali-sattari** [olivernn/davis.js#66]
Let's say I have an app with some get routes defined.

In some cases I need to manually trigger one of these routes by passing a path as string.
I don't know which route it might belong to, so I need Davis to act as if a link has been clicked.
I know there is state and trans methods available, but it doesn't cover my need.

How can I trigger/parse from within an app object or from outside that object?

**Comment by olivernn** [comment]
It is possible to manually run a route:

```
var app = Davis(function () {
    this.get('/foo', function (req) {
        // your code here
    })
})
```

Given the app above, you can manually run that route by [finding the route](http://olivernn.github.com/davis.js/docs/#lookupRoute), and then [running](http://olivernn.github.com/davis.js/docs/#run) it against a request:

```
var route = app.lookupRoute('get', '/foo')
```

This will give you a route object which you can now run by calling its `run` method and passing in a request object.

```
var request = new Davis.Request ('/foo')
route.run(request)
```

All route level middleware and the route handler will be called using the request you pass to run.

**Comment by ali-sattari** [comment]
Thanks, that's pretty much what I've worked out from documents, except the request part.
It might come in handy to have a parse or trigger method for app object to do these.

**Comment by briandastous** [comment]
If you want to both trigger the route and change the URL in the browser location bar (as occurs when clicking a link or submitting a form), try using `Davis.location.assign` instead of `route.run`:

```
Davis.location.assign(new Davis.Request('/foo'));
```

**Comment by shash7** [comment]
Works like a charm. Thanks a ton.

**Comment by nsisodiya** [comment]
I think, we need to document somewhere the use for `Davis.location.assign`

here is what I was doing due to ignorance

```
window.setTimeout(function() {
        var a = document.createElement("a");
        a.setAttribute("href", url);
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      }, 0);
```

Now I can simply use 

```
Davis.location.assign(new Davis.Request(url));
```
