### ISSUE TITLE
Davis does not correctly escape characters when submitting forms and thus sets the wrong URL

### ISSUE THREAD

**Issue by Valloric** [olivernn/davis.js#70]
1. Assume there's an `<input type="search" name="query">` inside a form that submits a GET request.
2. Set the value of the field to `foo bar &zoo=goo`.
3. Submit the form.
4. See the query part of the URL change to `?query=foo%20bar%20&zoo=goo` instead of to
   `?query=foo+bar+%26zoo%3Dgoo` (`%20` instead of `+` would be fine as well, but the `&` and `=` characters need to be escaped).

**Comment by olivernn** [comment]
Thanks for reporting this, I've pushed a new version that fixes this [0.9.8](https://github.com/olivernn/davis.js/tree/v0.9.8)

**Comment by Valloric** [comment]
Thanks!

**Comment by olivernn** [comment]
No worries, I actually screwed up the 0.9.8 release, so don't use that - 0.9.9 is the latest
