### ISSUE TITLE
absolute paths?

### ISSUE THREAD

**Issue by stoplion** [olivernn/davis.js#71]
Can Davis detect a route posting to an external URL? Here i am trying to send email via an external service. I can't seem to match the route..

```
form action="http://localhost:4322/send_mail" method="post"
        .field
            textarea name="message" placeholder="Say Hello.." autofocus="autofocus"
        .field
            input type="text" name="email" placeholder="your email"
        .field
            input type="submit" name="submit" value="submit" class="fat button full"
```

**Comment by stoplion** [comment]
Or as an alternative a way to match all outbound Posts? Or even all Posts in general. 

```
@post '*path', ->
```

**Comment by olivernn** [comment]
Davis can detect paths to an external URL, it specifically ignores them. This is because using pushState you can only change the path, not the host etc, so there isn't much Davis can do with external URLs.

You can match all outbound posts by using a regex as the path parameter, e.g.

```
this.post(/.+/, function (req) {
  // do stuff here
})
```

**Comment by stoplion** [comment]
awesome, thanks.
