### ISSUE TITLE
Programatically running a route doesn't pushState into the browser history

### ISSUE THREAD

**Issue by mauricio-morales** [olivernn/davis.js#76]
Hi,

So I found issue #66 and the answers successfully run a route programatically. However, the browser's URL doesn't get updated (which is why the app.trans function doesn't work for me, cause I need a state switch there).

Is there something I can do to actually have the pushState updated (short of doing the pushState myself?)

**Comment by cnizzardini** [comment]
Not sure if I follow exactly what you are looking for, but have you tried something like this to force update the state:

```
            var request = new Davis.Request({
              title: "My Route",
              fullPath: "/my_route/index",
              method: "get"
            })
            Davis.location.assign(request);
```

_edit_ After re-reading I see you are trying to avoid doing this. Tried helping at least. Good luck.

**Comment by briandastous** [comment]
Try this:

```
Davis.location.assign(new Davis.Request(url))
```

**Comment by mauricio-morales** [comment]
Davis.location.assign(new Davis.Request(url))

That did the trick. Excelent! Thanks briandastous.
