### ISSUE TITLE
Routes doesn't trigger on page load

### ISSUE THREAD

**Issue by odyssomay** [olivernn/davis.js#78]
I have this in a script on my page:

``` javascript
var app = Davis(function() {
  this.get("/", function(req) {
    console.log("/");
  });

  this.get(".*", function(req) {
    console.log("404");
  });
});

app.start()
```

Everything works fine when I click on a link, but not when reloading or writing the url manually. So am I doing something wrong or is this a problem with davis?

**Comment by thasmo** [comment]
That's a configuration option:

```
var router = Davis(function() {
    this.configure(function(settings) {
        settings.generateRequestOnPageLoad = true;
    });
});
```

**Comment by odyssomay** [comment]
Oh ok. Thanks! :)

**Comment by geniuscarrier** [comment]
Same issue, clicking on a link works fine. But reloading, it always says

"Not Found
The requested URL /home was not found on this server."

Do I miss something? I am working with version 0.9.9. 

<pre>
    var app = Davis(function() {
        this.configure(function(settings) {
            settings.generateRequestOnPageLoad = true
        });
        this.get("/home", function (req) {
            console.log("test")
        });
    });
    app.start();
</pre>

**Comment by arthur24b6** [comment]
@geniuscarrier it sounds like you're trying to load a path that you server doesn't know about- I'm guessing the path /home is defined in your davis app, not on your server.
