### ISSUE TITLE
POST routes defined within a scope don't work

### ISSUE THREAD

**Issue by thasmo** [olivernn/davis.js#80]
Something like this doesn't seem to get called at all:

```
this.scope('/:language', function() {
    this.post('/search', searchController);
});
```

If `this.post` gets changed to `this.get` it will work again.

By the way - has development on davis.js
stalled or is it being developed actively still?

**Comment by thasmo** [comment]
Aw, sorry - my mistake. This _does_ work well!

**Comment by olivernn** [comment]
Development has definitely slowed on this project. I have some ideas of what needs to happen to move towards a 1.0 release, but I have been very busy in the past few months.

I'm always grateful for support by other users of the library and would be more than happy to merge pull requests and even grant people commit access to make sure the current version is maintained better.

**Comment by thasmo** [comment]
It would be awesome to see development of davis.js moving on - it's a great library. There're some pull requests open - are you going to have a look at it? As I'm not that experienced in JavaScript I'm not a great help in maintainance etc. Hopefully someone else will help you out. Or maybe you'll find some more time for it. ;)
